[package]
name = "wik_dps_tp01"
version = "0.1.0"
edition = "2021"
# the binary and its permissions
[[bin]]
name = "app"
path = "src/main.rs"
test = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
